spring:
  datasource:
    url: jdbc:mysql://localhost:3306/upvet
    username: UpVet
    password: K#3oV>cZ1bv2
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql:
     init:
       mode: embedded
  jpa:  
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
loggin:
 level:
  br.com.marcos: DEBUG
api:
   security:
     token:
       secret: ${JWT_SECRET:14j06y25t}
server:
  ssl:
   enabled: true                    # Corrigido aqui: 'enabled' e indentação
   key-store: file:/home/keystore.p12
   key-store-password: Pass9500       # Coloque a senha correta aqui
   key-store-type: PKCS12
   key-alias: springboot

