spring:
  datasource:
    url: jdbc:mysql://localhost:3306/upvet
    username: root
    password: Marcos@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:  
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
loggin:
 level:
  br.com.marcos: DEBUG
api:
   security:
     token:
       secret: ${JWT_SECRET:14j06y25t}